```{js, echo = FALSE}
document.title = "Research"
```

<div align="center">
# Research 
<div>


****

<div align="justify">

### <ins> Peer Reviewed Publications </ins>

<br />


**The Civic Side of Tax Compliance: Evidence from Italy**, *with* <a href="https://sites.google.com/view/francescacalamunci/home?authuser=0" target="_blank">*Francesca Calamunci*</a>

<a href="https://www.sciencedirect.com/science/article/abs/pii/S0165176525001831" target="_blank">*Economics letters*</a> *(2025)*

<details close>
<summary>*Abstract*</summary> This study validates TV fee compliance as a proxy for civic capital in Italy. Using municipality-level
data, we show that it strongly correlates with traditional social capital measures such as voluntary
associations, referenda, and European elections turnout. The analysis confirms its reliability both at
municipal and provincial levels. TV fee compliance provides a scalable, objective, and timely indicator,
particularly useful for researchers to examine the socio-economic dynamics of civic capital and its
implications for institutional performance and economic development.
</details>

<br />

**Setting an example: political leaders’ cues and health behavior in the early stages of the COVID-19 pandemic in Mexico**, *with* <a href="https://sites.google.com/view/brunomorando/home" target="_blank">*Bruno Morando*</a> *and* <a href="https://www.udlap.mx/ofertaacademica/profesores.aspx?cveCarrera=LEC&profesor=0024068&extracto=1" target="_blank">*Luciano Ayala Cantu*</a>

<a href="https://onlinelibrary.wiley.com/doi/10.1111/lamp.12223" target="_blank">*Latin American Policy*</a> *(2021)*

<details close>
<summary>*Abstract*</summary> How do political leaders’ cues affect citizen behavior regarding a new and complex issue? We address this question in the context of the early stages of the Covid‐19 pandemic in Mexico, using electoral outcomes and municipal‐level mobility data from Facebook's Movement Range Maps. In March 2020, Mexico's president downplayed constantly the severity of the coming health crisis by continuing his political rallies throughout the country and encouraging people to leave their homes. Using an event‐study analysis, we find that, after the first press conference where his government declared mobility restrictions were not yet necessary, on March 13, citizens’ geographic mobility in pro‐government municipalities was higher than in cities where support for the president was less strong. Our results are robust to several specifications and definitions of political support. Moreover, we find evidence that our results are driven by cities with higher media penetration, which implies that they can be attributed to people's reactions to the president's cues rather than to systematic differences in the preferences of his supporters.
</details>

<br />


<br />


### <ins> Working Papers </ins>

<br />


**When Crime Tears Communities Apart: Social Capital and Organised Crime**, 
*with* <a href="https://sites.google.com/view/francescacalamunci/home?authuser=0" target="_blank">*Francesca Calamunci*</a>

*<a href="https://papers.ssrn.com/sol3/papers.cfm?abstract_id=4431634" target="_blank">**Most recent draft**</a>*, updated version coming soon!

*Status: Conditionally accepted at The Journal of Law, Economics & Organization*

<details close>
<summary>*Abstract*</summary> What is the long-term effect of organised crime presence on civic capital? By leveraging novel tax compliance and organised crime data, this study investigates this question within the Italian landscape from the 1950s to the 2000s. We exploit the forced resettlement law that compelled organised crime members living in the South of Italy to resettle in the Centre-North area of the country. Employing a difference-in-differences estimation strategy, estimates reveal that sustained exposure to mafia presence reduces TV tax compliance. Exploring possible mechanisms, we find that municipalities exposed to the forced resettlement law show more firms in strategic sectors for organised crime infiltration, and more episodes of extortion and labour racketeering.  
</details>

<br />


**Does Green Re-industrialization Pay off? Impacts on Employment, Wages and Productivity**, *with* <a href="https://sites.google.com/view/fbontadini/home" target="_blank">*Filippo Bontadini*</a> *and* <a href="https://sites.google.com/view/francescovona/home" target="_blank">*Francesco Vona*</a>   

*<a href="https://feem-media.s3.eu-central-1.amazonaws.com/wp-content/uploads/NDL2024-23-1.pdf" target="_blank">**Most recent draft**</a>*

*Status: submitted*

<details close>
<summary> *Abstract* </summary> What are the consequences of green industrialization on the labour market and industry dynamics? This paper tackles and quantifies this question by employing observable and reliable data on green manufacturing production for an extensive set of EU countries and 4-digit manufacturing industries for over a decade. First, at a descriptive level, this paper documents that green production is mostly concentrated in a few countries and industries. Moreover, potentially green industries outperform the others in terms of employment, average wages, value added and productivity. Second, when controlling for other drivers of the labour market and industry dynamics in the econometric analysis, it finds that employment and value added grow faster in potentially green sectors, particularly at the intensive margin. In contrast, average wages and labour productivity remain unchanged. Then, to purge the analysis from possible endogeneity, this paper employs two shift-share instruments. These econometric exercises corroborate the previous findings. An increase in 1 million€ of sold green production is associated with an increase of 0.03% in employment and value added, respectively. The analysis is extended with different heterogeneity exercises and robustness checks.
</details>

<br />

**The Local Job Multipliers of Green Re-industrialization**, *with* <a href="https://sites.google.com/view/fbontadini/home" target="_blank">*Filippo Bontadini*</a>, <a href="https://sites.google.com/view/italocolantone/home?authuser=0" target="_blank">*Italo Colantone*</a> *and* <a href="https://sites.google.com/view/francescovona/home" target="_blank">*Francesco Vona*</a>   

*<a href="https://feem-media.s3.eu-central-1.amazonaws.com/wp-content/uploads/NDL2025-13.pdf" target="_blank">**Most recent draft**</a>*, *<a href="https://www.ifo.de/DocDL/cesifo1_wp11939.pdf" target="_blank">**CESifo working paper**</a>*


*Status: submitted*

<details close>
<summary>*Abstract*</summary> What are the job multipliers of the green industrialization? We tackle this question within EU regions over the period 2003-2017, building a novel measure of green manufacturing penetration that combines green production and regional employment data. We estimate local job multipliers of green penetration in a long-difference model, using a shift-share instrument that exploits plausibly exogenous changes in non-EU green innovation. We find that a 3-years change in green penetration per worker increases the employment-to-active population ratio by 0.11 pp. The effect is: persistent both in manufacturing and outside manufacturing; halved by agglomeration effects that increase the labour market tightness; stronger for  workers with high and low-education; and present also in regions specialized in polluting industries. When focusing on large shocks in a staggered DiD design, we find ten times larger effects, particularly in earlier periods.
</details>

<br />

**Vaccines on the Move and the War on Polio**, *with* <a href="https://sites.google.com/view/lauramunozblanco/home?authuser=0" target="_blank">*Laura Muñoz Blanco*</a>

*<a href="https://exetereconomics.github.io/RePEc/dpapers/DP2403.pdf" target="_blank">**Most recent draft**</a>*

*Status: submitted*

<details close>
<summary>*Abstract*</summary> The rising number of refugees and internally displaced people (IDPs) presents new challenges for vaccine distribution and the spread of diseases. How do forcibly displaced population inflows affect infectious diseases incidence in host communities? Can a policy intervention that vaccinates children during their migration mitigate the impacts? To answer these questions, we examine the Pakistani mass internal displacement from the conflict-affected Federally Administered Tribal Areas in 2008. Using a difference-in-differences approach, we compare new polio cases in districts near and far from the conflict zone before and after 2008. The spatial distribution of districts relative to the historical region of Pashtunistan allows us to design a sample of comparable units. We show that a standard deviation increase in predicted IDP inflow leads to a rise in the new polio cases per 100,000 inhabitants. Poorer vaccination levels among IDP compared to native children in host communities are one of the main mechanisms. Implementing a vaccination policy targeting IDP children during their migration journey helps bridge the vaccination gap, with important welfare implications. 
</details>

<br />


**Political Participation and Competition in Concurrent Elections** 

*<a href="https://feem-media.s3.eu-central-1.amazonaws.com/wp-content/uploads/NDL2025-15.pdf" target="_blank">**Most recent draft**</a>*

*Status: submitted*

<details close>
<summary>*Abstract*</summary> This paper investigates how concurrent national and local elections affect the local political participation and competition. Leveraging a quasi-experimental framework provided by Italy’s staggered electoral timing, the paper employs a difference-in-differences design. Estimates reveal that municipalities holding concurrent elections exhibit lower levels of local participation and competition. Moreover, the concurrent election increases participation by candidates with nationally-established parties, while decreases participation with independent parties. This further translates into a higher votes share for nationally-established parties and a consequent higher probability of election. Elected mayors tend to have lower education and experience in office, while they are more likely to be from the municipality they were elected in. Further, elected mayors are able to attract more intergovernmental transfers, without substantially affecting local spending patterns.
</details>

<br />

**Identity Rhetoric and Tax Evasion**, *with* <a href="https://sites.google.com/view/francesco-barilari/home" target="_blank">*Francesco Barilari*</a>, <a href="https://sites.google.com/view/francescacalamunci/home" target="_blank">*Francesca Calamunci*</a> *and* <a href="https://sites.google.com/view/diegozambiasi/home" target="_blank">*Diego Zambiasi*</a>

*<a href="https://download.ssrn.com/2025/8/12/5388466.pdf?response-content-disposition=inline&X-Amz-Security-Token=IQoJb3JpZ2luX2VjEMv%2F%2F%2F%2F%2F%2F%2F%2F%2F%2FwEaCXVzLWVhc3QtMSJIMEYCIQC1udi0eVv8EX2xh21YKVIWRdCoBpoLVNw46HAmv62xmwIhAN8F3ShvBKugMZjv9Ze6sTHHT6SDnMDUh%2BlfOoG5HYhJKr0FCBQQBBoMMzA4NDc1MzAxMjU3Igx4jc6PZ0lv1bdBKFMqmgUVXc2F4nqcGSuUAZ8wlHXIyarjE47Scf8z4YXOAl1%2F00uIlp4dkoHWJH1OPhSD68EMMprXEkfiDf5CLIbSMAjG6iAJRgneKaz0uZFgfwkD0YLtewFK6XcGhzQwUQBE1hV%2FYhrpvYVTadUA0%2F7BvBCNzlQhCeIMGuRMuHKashhrLIsp36KtT27wNR%2FEc5g3NIfbvDNg6%2FfsptFG5Uz0A%2F0vcF8t6%2BN5Cja5RWNdp75P%2BvniKtL7ML5sd5BZtC56LNxngjReVZYbp7%2FfaH8%2FDd%2FMVU0DmeiHvrr5Nu2yAAMLh034y%2FdkOSCfGRpyehdtXMvzebg1nUj8UgqJbTPxpM7ykKVXpu8VJcL0CVN9K2od%2BeGPnylK2tcnZrH4OGETOYcxo7eg77hCaeXfDHnhYW0tz%2BCwPjKuSJh%2BdGNG48w19trlAV7x%2FbD70T5yDWDBdZvSkjHY%2FDwHVrRwTNQmq3MTiaupms6luuGi8FKCAy9Twwjm1fPYgJtNgFiGlMEeJ%2F%2BXsf%2ByFogvNZyNf%2F0F54GUwukeSbLatknGjC8bw8gOZDtXMNukMncQYxQIq0QPXaw6BcIHvjitVPw6HgOVIoFzQvWXARVUPEKhYEd7%2FTk3FpZ6WHxehRDLWyJsEvzThopmaQ8AHy%2FpujIMEeQBfYa3Fsog%2FKV88kcHA7Sl8wcFOYQgp052nmQvNgCtNU1t%2BGYnuwvLblPtWsiPFRHnls3TOzRzI6yyt8TtbwErmIaAOcdjSq7xbbaqBNemzjKyTr%2Fx%2BkPJB1EJCE4qPiiMvJWbxC0%2F7ewg4kF4iX%2FvNdloxlXnC3F1nPygP8wFWMnbo9FFHgBy9qDlhGgybd7HzSRORCpGpN5CfA5qdvbNP1jmG1Vao19TKPLfYC0wnL3sxAY6sAHhhDM83DuIB5uQ9sEpNx8mbcmczqsxWigQ4stHT%2BDf0QNUiX694HN0YfwU4pP%2BDlrYTL77V9yZfn1Uc0F%2F5tO0BC3dR15GNDSfHeYLuwdC5EnOARfztB5QAWNfoE8yx9Swx0FvpCeTyog8leoi1Dex3dHvNniKudUaGK6uDVvulSZwUr5AzJULcGz40axVNTH9MmTtHT814rOiEz4C0OFQWqUFizLZW285XJryZ1b3IA%3D%3D&X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Date=20250812T114650Z&X-Amz-SignedHeaders=host&X-Amz-Expires=300&X-Amz-Credential=ASIAUPUUPRWEROFSUCHZ%2F20250812%2Fus-east-1%2Fs3%2Faws4_request&X-Amz-Signature=c04bbb49c6fd2755bed7affd2a0b50ce90886e2e63e26eecee6351ea5fd4e918&abstractId=5388466" target="_blank">**Most recent draft**</a>*


*Status: next to submission*

<details close>
<summary>*Abstract*</summary> This paper studies how identity-based political rhetoric can erode tax compliance. We focus on Italy's Northern League (NL), a regionalist party that framed national taxes as an illegitimate imposition by a distant and exploitative central government. Exploiting the staggered local entry of NL into municipal elections between 1990 and 2015, we implement a difference-indifferences design to estimate the causal effect of exposure to NL's rhetoric on tax compliance. We find that NL participation leads to a significant decline in payment of the national TV license fee, a symbolically charged and centrally collected tax. The effect is absent for local taxes and unrelated parties like Forza Italia, and is not driven by NL's control of local government. The decline is amplified in municipalities with higher initial support for NL, greater exposure to its television channel, and more intense local campaign activity. The effect is also stronger in economically vulnerable communities. Taken together, the evidence points to a rhetorical mechanism: repeated exposure to a narrative that casts national taxation as cultural exploitation weakens compliance with central fiscal obligations. 
</details>

<br />

<br />

### <ins> Selected work in progress </ins>

<br />

**Wage and skills gaps for green jobs in Europe**, *with* <a href="https://leannecass.com/" target="_blank">*Leanne Cass*</a>, <a href="https://aureliensaussay.github.io/" target="_blank">*Aurélien Saussay*</a>, <a href="https://personal.lse.ac.uk/satom/" target="_blank">*Misato Sato*</a> *and*  <a href="https://sites.google.com/view/francescovona/home" target="_blank">*Francesco Vona*</a> 

*Status: writing first draft*

<br />

**Organised crime and human capital, within-city evidence from Italy** 

*Status: resting*


